"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Download, LoaderCircle, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Estado, Requerimiento } from "@/lib/types";
import { Alert } from "@/components/ui/alert";

const states:Estado[]=["Pendiente","Atendido","Observado"];
export function AdminRequirements({initial}:{initial:Requerimiento[]}){
  const [rows,setRows]=useState(initial); const [query,setQuery]=useState(""); const [state,setState]=useState(""); const [busy,setBusy]=useState(""); const [loadingMore,setLoadingMore]=useState(false); const [hasMore,setHasMore]=useState(initial.length===50); const [exporting,setExporting]=useState(false); const [notice,setNotice]=useState<{kind:"success"|"error";text:string}|null>(null);
  const filtered=useMemo(()=>rows.filter(r=>{const matches=!query||[r.profiles?.nombre,r.profiles?.email,r.personal?.nombre,r.personal?.dni,r.personal?.cliente,r.personal?.unidad].some(v=>v?.toLowerCase().includes(query.toLowerCase())); return matches&&(!state||r.estado===state);}),[rows,query,state]);
  async function update(id:string,estado:Estado){if(busy)return;setBusy(id);setNotice(null);const {error}=await createClient().from("requerimientos").update({estado}).eq("id",id);if(!error){setRows(x=>x.map(r=>r.id===id?{...r,estado}:r));setNotice({kind:"success",text:"Estado actualizado correctamente."});}else setNotice({kind:"error",text:"No se pudo actualizar el estado."});setBusy("");}
  function exportCsv(){if(exporting)return;setExporting(true);const link=document.createElement("a");link.href="/api/admin/requerimientos/csv";link.click();window.setTimeout(()=>setExporting(false),1800);}
  async function loadMore(){if(loadingMore)return;setLoadingMore(true);setNotice(null);const {data,error}=await createClient().from("requerimientos").select("id,fecha,referencia_interna,estado,personal(nombre,dni,cargo,cliente,unidad),profiles(nombre,email)").order("fecha",{ascending:false}).range(rows.length,rows.length+49);if(error){setNotice({kind:"error",text:"No se pudieron cargar más registros."});setLoadingMore(false);return;}const next=(data??[]) as unknown as Requerimiento[];setRows(current=>[...current,...next]);setHasMore(next.length===50);setLoadingMore(false);}
  return <>{notice&&<div className="mb-3"><Alert kind={notice.kind}>{notice.text}</Alert></div>}<div className="mb-4 grid gap-2 sm:grid-cols-[minmax(260px,1fr)_190px_auto]"><div className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#607089]" size={18}/><input className="input !pl-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por supervisor, agente, DNI..."/></div><select className="input" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option>{states.map(s=><option key={s}>{s}</option>)}</select><button disabled={exporting} className="btn btn-secondary" onClick={exportCsv}>{exporting?<LoaderCircle className="animate-spin" size={17}/>:<Download size={17}/>} {exporting?"Exportando...":"Exportar CSV"}</button></div>
    <div className="card overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-[#DCE3EC] bg-[#F8FAFD] text-xs font-medium text-[#607089]"><tr>{["Fecha","Supervisor","Agente","DNI","Cliente · Unidad","Estado",""] .map((h,i)=><th className="px-4 py-3" key={i}>{h}</th>)}</tr></thead><tbody className="divide-y divide-[#E8EDF4]">{filtered.map(r=><tr key={r.id} className="hover:bg-[#FBFCFE]"><td className="whitespace-nowrap px-4 py-3 text-xs text-[#607089]">{new Intl.DateTimeFormat("es-PE").format(new Date(r.fecha))}</td><td className="px-4 py-3 text-sm">{r.profiles?.nombre||r.profiles?.email}</td><td className="px-4 py-3 text-sm font-medium">{r.personal?.nombre}</td><td className="px-4 py-3 text-sm">{r.personal?.dni}</td><td className="px-4 py-3 text-sm">{r.personal?.cliente} · {r.personal?.unidad}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><select disabled={Boolean(busy)} className="h-9 rounded-lg border border-[#CBD5E1] bg-white px-2 text-sm" value={r.estado} onChange={e=>update(r.id,e.target.value as Estado)}>{states.map(s=><option key={s}>{s}</option>)}</select>{busy===r.id&&<LoaderCircle className="animate-spin text-[#2563EB]" size={16}/>}</div></td><td className="px-4 py-3"><Link className="text-sm font-medium text-[#174EA6]" href={`/requerimientos/${r.id}`}>Ver detalle</Link></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-6 text-center text-sm text-[#607089]">No hay resultados para los filtros seleccionados.</p>}</div>{hasMore&&<button className="btn btn-secondary mx-auto mt-3 flex" disabled={loadingMore} onClick={loadMore}>{loadingMore&&<LoaderCircle className="animate-spin" size={17}/>} {loadingMore?"Cargando...":"Cargar más"}</button>}</>;
}
