"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Download, LoaderCircle, Search } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import type { Estado, Requerimiento } from "@/lib/types";

const states:Estado[]=["Pendiente","Atendido","Observado"];
export function AdminRequirements({initial}:{initial:Requerimiento[]}){
  const [rows,setRows]=useState(initial); const [query,setQuery]=useState(""); const [state,setState]=useState(""); const [busy,setBusy]=useState(""); const [loadingMore,setLoadingMore]=useState(false); const [hasMore,setHasMore]=useState(initial.length===50);
  const filtered=useMemo(()=>rows.filter(r=>{const matches=!query||[r.profiles?.nombre,r.profiles?.email,r.personal?.nombre,r.personal?.dni,r.personal?.cliente,r.personal?.unidad].some(v=>v?.toLowerCase().includes(query.toLowerCase())); return matches&&(!state||r.estado===state);}),[rows,query,state]);
  async function update(id:string,estado:Estado){setBusy(id);const {error}=await createClient().from("requerimientos").update({estado}).eq("id",id);if(!error)setRows(x=>x.map(r=>r.id===id?{...r,estado}:r));setBusy("");}
  function exportCsv(){const link=document.createElement("a");link.href="/api/admin/requerimientos/csv";link.click();}
  async function loadMore(){setLoadingMore(true);const {data}=await createClient().from("requerimientos").select("id,fecha,referencia_interna,estado,personal(nombre,dni,cargo,cliente,unidad),profiles(nombre,email)").order("fecha",{ascending:false}).range(rows.length,rows.length+49);const next=(data??[]) as unknown as Requerimiento[];setRows(current=>[...current,...next]);setHasMore(next.length===50);setLoadingMore(false);}
  return <><div className="card mb-5 grid gap-3 p-4 sm:grid-cols-[1fr_190px_auto]"><div className="relative"><Search className="absolute left-4 top-3.5 text-slate-400" size={20}/><input className="input pl-12" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por supervisor, agente, DNI..."/></div><select className="input" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option>{states.map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-primary" onClick={exportCsv}><Download size={18}/>Exportar CSV</button></div>
    <div className="card overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Fecha","Supervisor","Agente","DNI","Cliente · Unidad","Estado",""] .map((h,i)=><th className="p-4" key={i}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(r=><tr key={r.id}><td className="p-4 whitespace-nowrap">{new Intl.DateTimeFormat("es-PE").format(new Date(r.fecha))}</td><td className="p-4">{r.profiles?.nombre||r.profiles?.email}</td><td className="p-4 font-bold">{r.personal?.nombre}</td><td className="p-4">{r.personal?.dni}</td><td className="p-4">{r.personal?.cliente} · {r.personal?.unidad}</td><td className="p-4"><select disabled={busy===r.id} className="rounded-lg border border-slate-300 p-2" value={r.estado} onChange={e=>update(r.id,e.target.value as Estado)}>{states.map(s=><option key={s}>{s}</option>)}</select></td><td className="p-4"><Link className="font-bold text-blue-700" href={`/requerimientos/${r.id}`}>Ver detalle</Link></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-slate-500">No hay resultados para los filtros seleccionados.</p>}</div>{hasMore&&<button className="btn mx-auto mt-4 flex bg-white text-blue-700 shadow-sm" disabled={loadingMore} onClick={loadMore}>{loadingMore&&<LoaderCircle className="animate-spin" size={18}/>}Cargar más</button>}</>;
}
