"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { LoaderCircle,Search,ToggleLeft,ToggleRight } from "lucide-react";
import { AdminSectionNav } from "@/components/admin-section-nav";
import { Alert } from "@/components/ui/alert";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Toast } from "@/components/ui/toast";
import type { CatalogKind,CatalogResult } from "@/lib/admin/maintenance";

const catalogs:{id:CatalogKind;label:string}[]=[{id:"clientes",label:"Clientes"},{id:"unidades",label:"Unidades"},{id:"personal",label:"Personal"},{id:"prendas",label:"Prendas"}];
type Client={id:string;nombre:string}; type Row=Record<string,unknown>&{id:string;activo:boolean};
const empty:CatalogResult={rows:[],total:0,page:1,pageSize:50};
function value(row:Row,key:string){const result=row[key];return result===null||result===undefined||result===""?"—":String(result)}
export function AdminMaintenance({clients}:{clients:Client[]}){
  const [catalog,setCatalog]=useState<CatalogKind>("clientes"),[query,setQuery]=useState(""),[client,setClient]=useState(""),[gender,setGender]=useState("");
  const [result,setResult]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState(""),[target,setTarget]=useState<Row|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
  const abort=useRef<AbortController|null>(null);
  const load=useCallback(async(page=1,nextCatalog=catalog)=>{abort.current?.abort();const controller=new AbortController();abort.current=controller;setLoading(true);setError("");try{const params=new URLSearchParams({catalogo:nextCatalog,q:query,page:String(page)});if(client)params.set("cliente",client);if(gender)params.set("genero",gender);const response=await fetch("/api/admin/catalogos?"+params,{cache:"no-store",signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"No se pudo consultar el catálogo.");}finally{if(abort.current===controller)setLoading(false)}},[catalog,query,client,gender]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(1),query?250:0);return()=>{window.clearTimeout(timer);abort.current?.abort()}},[load,query]);
  function changeCatalog(next:CatalogKind){setCatalog(next);setQuery("");setClient("");setGender("");setResult(empty)}
  async function toggle(){if(!target||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/admin/catalogos",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({catalogo:catalog,id:target.id,activo:!target.activo})});const data=await response.json();if(!response.ok)throw new Error(data.error);setTarget(null);setToast(`Registro ${data.activo?"activado":"desactivado"} correctamente`);await load(result.page);}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar el registro.");}finally{setBusy(false)}}
  const rows=result.rows as Row[],pages=Math.max(1,Math.ceil(result.total/result.pageSize));
  const fields=catalog==="clientes"?["nombre"]:catalog==="unidades"?["nombre","clientes"]:catalog==="personal"?["codigo_personal","nombre","dni","cargo"]:["codigo_prenda","nombre_prenda","cliente","genero","cantidad","precio"];
  const label:Record<string,string>={nombre:"Nombre",clientes:"Cliente",codigo_personal:"Código",dni:"DNI",cargo:"Cargo",codigo_prenda:"Código",nombre_prenda:"Prenda",cliente:"Cliente",genero:"Género",cantidad:"Cant.",precio:"Precio"};
  return <section className="min-w-0"><AdminSectionNav/><header className="page-header"><p className="page-eyebrow">Administración</p><h1 className="page-title">Mantenimiento</h1><p className="page-description">Activa o desactiva catálogos sin borrar información histórica.</p></header>
    <div className="card p-4 sm:p-5"><div role="tablist" aria-label="Catálogos" className="flex gap-1 overflow-x-auto border-b border-[var(--border)]">{catalogs.map(item=><button key={item.id} role="tab" aria-selected={catalog===item.id} className={`min-h-11 shrink-0 border-b-2 px-3 text-sm font-medium ${catalog===item.id?"border-[var(--brand-600)] text-[var(--brand-700)]":"border-transparent text-[var(--text-secondary)]"}`} onClick={()=>changeCatalog(item.id)}>{item.label}</button>)}</div>
      <div className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_220px_150px]"><div className="relative md:col-span-1"><Search size={17} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-secondary)]"/><input aria-label={`Buscar en ${catalog}`} className="input !pl-10" maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre o código"/></div>{(catalog==="unidades"||catalog==="prendas")&&<select aria-label="Filtrar por cliente" className="input" value={client} onChange={e=>setClient(e.target.value)}><option value="">Todos los clientes</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select>}{catalog==="prendas"&&<select aria-label="Filtrar por género" className="input" value={gender} onChange={e=>setGender(e.target.value)}><option value="">Todos los géneros</option><option>HOMBRE</option><option>MUJER</option><option>AMBOS</option></select>}</div></div>
    {error&&<div className="mt-4"><Alert kind="error">{error}</Alert></div>}<div className="mt-4 flex min-h-6 items-center justify-between"><h2 className="text-sm font-semibold text-[var(--brand-900)]">{result.total.toLocaleString("es-PE")} registros</h2>{loading&&<span className="flex items-center gap-2 text-xs text-[var(--text-secondary)]"><LoaderCircle size={15} className="animate-spin"/>Consultando...</span>}</div>
    <div className={`card mt-3 overflow-hidden ${loading?"opacity-60":""}`}>{!loading&&!rows.length?<p className="px-4 py-7 text-center text-sm text-[var(--text-secondary)]">No hay registros con estos filtros.</p>:<div className="divide-y divide-[var(--border)]">{rows.map(row=><article key={row.id} className="grid gap-3 px-4 py-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><dl className={`grid min-w-0 gap-x-5 gap-y-2 ${fields.length>2?"sm:grid-cols-2 xl:grid-cols-4":"sm:grid-cols-2"}`}>{fields.map(field=>{const raw=field==="clientes"?(row.clientes as {nombre?:string})?.nombre:value(row,field);return <div key={field} className="min-w-0"><dt className="text-xs text-[var(--text-secondary)]">{label[field]}</dt><dd className="mt-0.5 break-words text-sm font-medium">{field==="precio"?`S/ ${Number(raw).toFixed(2)}`:String(raw??"—")}</dd></div>})}</dl><div className="flex items-center justify-between gap-3 lg:justify-end"><span className={`text-xs font-semibold ${row.activo?"text-[var(--success)]":"text-[var(--text-secondary)]"}`}>{row.activo?"Activo":"Inactivo"}</span><button className="btn btn-ghost !px-3" disabled={busy} onClick={()=>setTarget(row)}>{row.activo?<ToggleRight size={18}/>:<ToggleLeft size={18}/>} {row.activo?"Desactivar":"Activar"}</button></div></article>)}</div>}</div>
    <nav aria-label="Paginación del catálogo" className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-[var(--text-secondary)]">Página {result.page} de {pages}</p><div className="flex gap-2"><button className="btn btn-secondary" disabled={loading||result.page<=1} onClick={()=>void load(result.page-1)}>Anterior</button><button className="btn btn-secondary" disabled={loading||result.page>=pages} onClick={()=>void load(result.page+1)}>Siguiente</button></div></nav>
    <ConfirmDialog open={Boolean(target)} busy={busy} intent="warning" title={target?.activo?"¿Desactivar este registro?":"¿Activar este registro?"} description="El cambio afectará los formularios nuevos, pero los requerimientos históricos conservarán sus datos." confirmLabel={target?.activo?"Sí, desactivar":"Sí, activar"} onCancel={()=>setTarget(null)} onConfirm={toggle}/><Toast message={toast} onClose={()=>setToast("")}/></section>;
}
