"use client";
import { useState } from "react";
import { FileUp,LoaderCircle,UploadCloud } from "lucide-react";
import { AdminSectionNav } from "@/components/admin-section-nav";
import { Alert } from "@/components/ui/alert";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { Toast } from "@/components/ui/toast";
import { parseCsv } from "@/lib/admin/csv-import";
import { IMPORT_HEADERS,type ImportKind,type ImportPreview } from "@/lib/admin/maintenance";

type Parsed={headers:string[];rows:Record<string,string>[]};
export function AdminImports(){const [kind,setKind]=useState<ImportKind>("personal"),[parsed,setParsed]=useState<Parsed|null>(null),[preview,setPreview]=useState<ImportPreview|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirming,setConfirming]=useState(false),[toast,setToast]=useState("");
  function reset(next=kind){setKind(next);setParsed(null);setPreview(null);setError("")}
  async function choose(file?:File){if(!file)return;setError("");setPreview(null);try{if(!file.name.toLowerCase().endsWith(".csv"))throw new Error("Selecciona un archivo CSV.");setParsed(parseCsv(await file.text()));}catch(e){setParsed(null);setError(e instanceof Error?e.message:"No se pudo leer el archivo.")}}
  async function request(mode:"preview"|"apply"){if(!parsed||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/admin/importaciones",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,headers:parsed.headers,rows:parsed.rows,mode})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(mode==="preview")setPreview(data);else{setConfirming(false);setToast(`Importación completada: ${data.nuevos} nuevos y ${data.actualizados} actualizados`);setParsed(null);setPreview(null)}}catch(e){setError(e instanceof Error?e.message:"No se pudo procesar la importación.");setConfirming(false)}finally{setBusy(false)}}
  const expected=IMPORT_HEADERS[kind].join(", ");
  return <section className="min-w-0"><AdminSectionNav/><header className="page-header"><p className="page-eyebrow">Administración</p><h1 className="page-title">Importaciones</h1><p className="page-description">Valida y confirma archivos CSV antes de actualizar los maestros.</p></header>
    <div className="section-card"><div className="grid gap-4 md:grid-cols-[220px_minmax(0,1fr)]"><div><label className="label" htmlFor="import-kind">Catálogo</label><select id="import-kind" className="input" value={kind} disabled={busy} onChange={e=>reset(e.target.value as ImportKind)}><option value="personal">Personal</option><option value="prendas">Prendas</option></select></div><div><span className="label">Encabezados requeridos</span><code className="block break-words rounded-lg bg-[var(--brand-50)] px-3 py-2.5 text-xs text-[var(--text-secondary)]">{expected}</code></div></div>
      <label className="mt-4 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#AEBBCF] bg-[#F8FAFD] px-4 py-5 text-center hover:border-[var(--brand-600)]"><UploadCloud size={22} className="text-[var(--brand-700)]"/><span className="mt-2 text-sm font-semibold">Seleccionar archivo CSV</span><span className="mt-1 text-xs text-[var(--text-secondary)]">Máximo 1 MB y 1,000 filas</span><input className="sr-only" type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label>
      {parsed&&<div className="mt-4 flex flex-col gap-3 border-t border-[var(--border)] pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm"><strong>{parsed.rows.length}</strong> filas listas para validar.</p><button className="btn btn-secondary" disabled={busy} onClick={()=>void request("preview")}>{busy?<LoaderCircle size={17} className="animate-spin"/>:<FileUp size={17}/>} Validar y previsualizar</button></div>}
    </div>
    {error&&<div className="mt-4"><Alert kind="error">{error}</Alert></div>}
    {preview&&<section className="card mt-4 overflow-hidden"><div className="border-b border-[var(--border)] px-4 py-4 sm:px-5"><h2 className="section-title">Vista previa</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Nuevos",preview.nuevos],["Actualizados",preview.actualizados],["Omitidos",preview.omitidos],["Errores",preview.errores]].map(([label,count])=><div key={String(label)}><p className="text-xs text-[var(--text-secondary)]">{label}</p><p className="mt-0.5 text-lg font-semibold tabular-nums text-[var(--brand-900)]">{count}</p></div>)}</div></div>
      {preview.issues.length?<div className="max-h-64 overflow-auto divide-y divide-[var(--border)]">{preview.issues.slice(0,100).map(issue=><div key={`${issue.row}-${issue.code}`} className="grid gap-1 px-4 py-3 text-sm sm:grid-cols-[70px_140px_minmax(0,1fr)] sm:px-5"><span className="text-[var(--text-secondary)]">Fila {issue.row}</span><strong className="break-words font-medium">{issue.code}</strong><span className={issue.action==="error"?"text-[var(--error)]":"text-[var(--warning)]"}>{issue.message}</span></div>)}</div>:<p className="px-4 py-5 text-sm text-[var(--success)] sm:px-5">Todas las filas son válidas.</p>}
      <footer className="flex flex-col-reverse gap-2 border-t border-[var(--border)] px-4 py-4 sm:flex-row sm:justify-end sm:px-5"><button className="btn btn-secondary" disabled={busy} onClick={()=>{setParsed(null);setPreview(null)}}>Cancelar</button><button className="btn btn-primary" disabled={busy||!preview.rows.length} onClick={()=>setConfirming(true)}>Confirmar importación</button></footer></section>}
    <ConfirmDialog open={confirming} busy={busy} intent="warning" title="¿Confirmar la importación?" description={`Se insertarán ${preview?.nuevos??0} registros y se actualizarán ${preview?.actualizados??0}. Los códigos existentes se actualizan; nunca se elimina información automáticamente.`} confirmLabel="Sí, importar" onCancel={()=>setConfirming(false)} onConfirm={()=>void request("apply")}/><Toast message={toast} onClose={()=>setToast("")}/>
  </section>;
}
