"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { CheckCircle2,ChevronLeft,ChevronRight,Download,Eye,ExternalLink,FileCheck2,ImageUp,Layers2,LoaderCircle,MessageSquareWarning,PenLine,Save,Send,Trash2,X,XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import type { DocumentStatus,Placement } from "@/lib/documents/types";
import type { Role } from "@/lib/types";
import type { PDFDocumentProxy } from "pdfjs-dist";
import { Alert } from "./ui/alert";
import { ConfirmDialog } from "./ui/confirm-dialog";

type WorkspacePlacement=Placement&{group?:string};
type Props={id:string;pages:number;status:DocumentStatus;role:Role;userId:string;creatorId:string;signerId:string;placements:Placement[];profileReady:boolean;profileAssetMode?:"DIBUJADA"|"IMPORTADA";coordinatorSigned:boolean;pdfType:"original"|"coordinador"|"firmado"|"base"};
const serialise=(items:WorkspacePlacement[],userId:string)=>JSON.stringify(items.filter(item=>item.usuario_id===userId).map(({tipo,pagina,x,y,ancho,alto})=>({tipo,pagina,x,y,ancho,alto})));

async function renderPdfPage(pdf:PDFDocumentProxy,pageNumber:number,host:HTMLElement,target:HTMLCanvasElement,isCurrent:()=>boolean){
 const pdfPage=await pdf.getPage(pageNumber);const rotation=pdfPage.rotate;const base=pdfPage.getViewport({scale:1,rotation});const scale=Math.min(1.7,Math.max(.45,(host.clientWidth-2)/base.width));const viewport=pdfPage.getViewport({scale,rotation});
 const buffer=document.createElement("canvas");buffer.width=Math.ceil(viewport.width);buffer.height=Math.ceil(viewport.height);await pdfPage.render({canvasContext:buffer.getContext("2d")!,viewport}).promise;
 if(!isCurrent())return false;target.width=buffer.width;target.height=buffer.height;target.style.aspectRatio=`${viewport.width}/${viewport.height}`;const context=target.getContext("2d")!;context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,target.width,target.height);context.drawImage(buffer,0,0);return true;
}

function DecisionDialog({kind,comment,busy,onComment,onCancel,onConfirm}:{kind:"observar"|"rechazar"|null;comment:string;busy:boolean;onComment:(value:string)=>void;onCancel:()=>void;onConfirm:()=>void}){
 if(!kind)return null;const observing=kind==="observar";
 return <div className="fixed inset-0 z-50 grid place-items-center bg-[#0B1F3A]/40 p-4" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onCancel()}}>
  <section role="dialog" aria-modal="true" aria-labelledby="decision-title" className="w-full max-w-md rounded-xl border border-[#DCE3EC] bg-white p-5 shadow-[0_18px_48px_rgba(11,31,58,.18)]"><div className="flex items-start justify-between gap-4"><div><h2 id="decision-title" className="text-lg font-semibold text-[#0B1F3A]">{observing?"Observar documento":"Rechazar documento"}</h2><p className="mt-1 text-sm text-[#607089]">El coordinador verá este comentario.</p></div><button className="rounded-lg p-2 text-[#607089] hover:bg-[#F5F8FD]" onClick={onCancel} aria-label="Cerrar"><X size={18}/></button></div>
  <label className="label mt-5" htmlFor="decision-comment">Motivo obligatorio</label><textarea autoFocus id="decision-comment" value={comment} onChange={event=>onComment(event.target.value)} maxLength={1000} className="input min-h-28 resize-y py-3" placeholder="Explica claramente qué debe revisar el coordinador."/>
  <div className="mt-5 grid gap-2 sm:grid-cols-2"><button className="btn btn-secondary" disabled={busy} onClick={onCancel}>Cancelar</button><button className={observing?"btn btn-primary":"btn btn-danger"} disabled={busy||!comment.trim()} onClick={onConfirm}>{busy&&<LoaderCircle className="animate-spin" size={16}/>}Confirmar</button></div></section>
 </div>
}

export function DocumentWorkspace(props:Props){
 const canvas=useRef<HTMLCanvasElement>(null);const wrap=useRef<HTMLDivElement>(null);const pdfRef=useRef<PDFDocumentProxy|null>(null);const basePdfRef=useRef<PDFDocumentProxy|null>(null);const loadedPdfType=useRef(props.pdfType);const renderSequence=useRef(0);
 const initial=useMemo(()=>props.placements as WorkspacePlacement[],[props.placements]);const initialKey=useMemo(()=>serialise(initial,props.userId),[initial,props.userId]);
 const [page,setPage]=useState(1);const [items,setItems]=useState<WorkspacePlacement[]>(initial);const [selected,setSelected]=useState<number|null>(null);const [savedKey,setSavedKey]=useState(initialKey);const [previewKey,setPreviewKey]=useState<string|null>(null);const [previewMode,setPreviewMode]=useState(false);const [busy,setBusy]=useState(false);const [loadingPdf,setLoadingPdf]=useState(true);const [message,setMessage]=useState("");const [decision,setDecision]=useState<"observar"|"rechazar"|null>(null);const [comment,setComment]=useState("");const [confirmSign,setConfirmSign]=useState<"coordinador"|"gerente"|null>(null);const router=useRouter();
 const canOwner=props.userId===props.creatorId&&props.role==="coordinador"&&["BORRADOR","OBSERVADO"].includes(props.status);
 const canOwnerPlace=canOwner&&!props.coordinatorSigned;const canManager=props.userId===props.signerId&&props.role==="gerente"&&props.status==="PENDIENTE_FIRMA";const canPlace=canOwnerPlace||canManager;
 const currentKey=serialise(items,props.userId);const dirty=currentKey!==savedKey;const previewed=currentKey===previewKey;const ownCount=items.filter(item=>item.usuario_id===props.userId).length;const canSend=props.coordinatorSigned||(!dirty&&previewed);
 const renderDocument=useCallback(async(pdf:PDFDocumentProxy,pageNumber:number)=>{const host=wrap.current?.parentElement,target=canvas.current;if(!host||!target)return;const sequence=++renderSequence.current;setLoadingPdf(true);try{const committed=await renderPdfPage(pdf,pageNumber,host,target,()=>sequence===renderSequence.current);if(committed)setLoadingPdf(false)}catch{if(sequence===renderSequence.current){setMessage("No se pudo mostrar el PDF.");setLoadingPdf(false)}}},[]);const draw=useCallback(async()=>{if(pdfRef.current)await renderDocument(pdfRef.current,page)},[page,renderDocument]);
 useEffect(()=>{let cancelled=false;let loaded:PDFDocumentProxy|null=null;(async()=>{try{const pdfjs=await import("pdfjs-dist");if(!pdfjs.GlobalWorkerOptions.workerSrc)pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();const suffix=props.pdfType==="original"?"":`?tipo=${props.pdfType}`;loaded=await pdfjs.getDocument(`/api/documentos/${props.id}/archivo${suffix}`).promise;if(!cancelled){basePdfRef.current=loaded;pdfRef.current=loaded;setPage(1);await renderDocument(loaded,1)}}catch{if(!cancelled){setMessage("No se pudo mostrar el PDF.");setLoadingPdf(false)}}})();return()=>{cancelled=true;renderSequence.current+=1;void loaded?.destroy()}},[props.id,props.pdfType,renderDocument]);
 useEffect(()=>{if(loadedPdfType.current!==props.pdfType){loadedPdfType.current=props.pdfType;setItems(initial);setSavedKey(initialKey);setPreviewKey(null);setPreviewMode(false)}},[initial,initialKey,props.pdfType]);
 useEffect(()=>{void draw()},[draw]);
 useEffect(()=>{const host=wrap.current?.parentElement;if(!host)return;let timer:ReturnType<typeof setTimeout>;const observer=new ResizeObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>void draw(),120)});observer.observe(host);return()=>{clearTimeout(timer);observer.disconnect()}},[draw]);
 function add(tipo:"FIRMA"|"SELLO"){if(!props.profileReady){setMessage("Configura primero tu perfil de firma y sello.");return}setSelected(items.length);setItems(value=>[...value,{tipo,pagina:page,x:.58,y:.68,ancho:tipo==="FIRMA"?.25:.32,alto:tipo==="FIRMA"?.1:.13,usuario_id:props.userId}])}
 function addGroup(){add("SELLO")}
 function remove(index:number){setSelected(null);setItems(current=>current.filter((_,itemIndex)=>itemIndex!==index))}
 function move(index:number,e:React.PointerEvent){setSelected(index);if(previewMode||items[index].usuario_id!==props.userId||!canPlace)return;const box=wrap.current?.getBoundingClientRect();if(!box)return;const startX=e.clientX,startY=e.clientY,origin=items[index];const snapshot=items;e.currentTarget.setPointerCapture(e.pointerId);
  const onMove=(event:PointerEvent)=>{const dx=(event.clientX-startX)/box.width,dy=(event.clientY-startY)/box.height;setItems(snapshot.map((item,i)=>{if(i!==index&&(!origin.group||item.group!==origin.group))return item;return{...item,x:Math.max(0,Math.min(1-item.ancho,item.x+dx)),y:Math.max(0,Math.min(1-item.alto,item.y+dy))}}))};
  const finish=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",finish)};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",finish);
 }
 function resize(index:number,e:React.PointerEvent){e.stopPropagation();if(previewMode||items[index].usuario_id!==props.userId||!canPlace)return;const box=wrap.current?.getBoundingClientRect();if(!box)return;const startX=e.clientX,startY=e.clientY,origin=items[index];const snapshot=items;
  const onMove=(event:PointerEvent)=>{const dx=(event.clientX-startX)/box.width,dy=(event.clientY-startY)/box.height;const scale=Math.max(.55,Math.min(1.8,1+Math.max(dx/origin.ancho,dy/origin.alto)));setItems(snapshot.map((item,i)=>{if(i!==index&&(!origin.group||item.group!==origin.group))return item;const anchorX=origin.group?Math.min(...snapshot.filter(x=>x.group===origin.group).map(x=>x.x)):origin.x;const anchorY=origin.group?Math.min(...snapshot.filter(x=>x.group===origin.group).map(x=>x.y)):origin.y;const ancho=Math.max(.06,Math.min(1-item.x,item.ancho*scale));const alto=Math.max(.04,Math.min(1-item.y,item.alto*scale));return{...item,x:anchorX+(item.x-anchorX)*scale,y:anchorY+(item.y-anchorY)*scale,ancho,alto}}))};
  const finish=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",finish)};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",finish);
 }
 async function action(accion:string,extra:Record<string,unknown>={}){
  setBusy(true);setMessage("");try{const response=await fetch(`/api/documentos/${props.id}/accion`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accion,...extra})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(accion==="colocaciones")setSavedKey(currentKey);setMessage(accion==="firmar"?"Documento firmado correctamente.":accion==="firmar_coordinador"?"Firma del coordinador incorporada correctamente.":"Cambio guardado correctamente.");router.refresh();return true}catch(error){setMessage(error instanceof Error?error.message:"No se pudo completar la acción.");return false}finally{setBusy(false)}
 }
 async function openPreview(){if(dirty){setMessage("Guarda la ubicación actual antes de generar la vista previa.");return}setBusy(true);setLoadingPdf(true);setMessage("");try{const response=await fetch(`/api/documentos/${props.id}/preview`,{method:"POST"});if(!response.ok){const data=await response.json();throw new Error(data.error)}const pdfjs=await import("pdfjs-dist");if(!pdfjs.GlobalWorkerOptions.workerSrc)pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await response.arrayBuffer())}).promise;const host=wrap.current?.parentElement;if(!host||!canvas.current)throw new Error("El visor no está disponible.");pdfRef.current=pdf;setPreviewMode(true);setSelected(null);await renderDocument(pdf,page)}catch(error){pdfRef.current=basePdfRef.current;setLoadingPdf(false);setMessage(error instanceof Error?error.message:"No se pudo generar la vista previa.")}finally{setBusy(false)}}
 function finishPreview(){setPreviewKey(currentKey);setPreviewMode(false);pdfRef.current=basePdfRef.current;void draw();setMessage("Vista previa PDF revisada. Ya puedes continuar.")}
 const own=items.filter(item=>item.usuario_id===props.userId).map(({tipo,pagina,x,y,ancho,alto})=>({tipo,pagina,x,y,ancho,alto}));
 const asset=(item:WorkspacePlacement)=>item.id?`/api/documentos/${props.id}/archivo?elemento=${item.id}`:`/api/perfil/firma?tipo=${item.tipo==="FIRMA"?"firma":"sello"}`;
 return <><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="card min-w-0 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#DCE3EC] px-3 py-2.5"><div className="flex flex-wrap gap-2">{canPlace&&!previewMode&&(props.profileAssetMode==="IMPORTADA"?<button onClick={addGroup} className="btn btn-secondary px-3"><ImageUp size={16}/>Imagen de firma</button>:<><button onClick={()=>add("FIRMA")} className="btn btn-secondary px-3"><PenLine size={16}/>Firma</button><button onClick={addGroup} className="btn btn-secondary px-3"><Layers2 size={16}/>Firma + sello</button></>)}</div><div className="flex items-center gap-1"><button className="btn btn-ghost px-2" disabled={page===1} onClick={()=>setPage(value=>value-1)} aria-label="Página anterior"><ChevronLeft size={18}/></button><span className="min-w-20 text-center text-xs font-medium text-[#607089]">Página {page} de {props.pages}</span><button className="btn btn-ghost px-2" disabled={page===props.pages} onClick={()=>setPage(value=>value+1)} aria-label="Página siguiente"><ChevronRight size={18}/></button></div></div>
  {previewMode&&<div className="flex flex-wrap items-center justify-between gap-3 border-b border-blue-200 bg-[#EAF2FF] px-4 py-3"><div><strong className="text-sm font-semibold text-[#0B1F3A]">Vista previa final</strong><p className="text-xs text-[#607089]">{canManager&&props.coordinatorSigned?"Revisa la firma del coordinador y tu firma sobre la versión intermedia.":"Recorre las páginas y verifica posición, escala y contenido."}</p></div><button className="btn btn-primary" onClick={finishPreview}><FileCheck2 size={17}/>He revisado la vista previa</button></div>}
  <div className="relative overflow-auto bg-[#E9EEF5] p-2 sm:p-5"><div ref={wrap} onPointerDown={event=>{if(event.target===event.currentTarget)setSelected(null)}} className="relative mx-auto w-fit max-w-full bg-white shadow-sm"><canvas ref={canvas} className="block h-auto max-w-full"/>{loadingPdf&&<div className="absolute inset-0 grid place-items-center bg-white/80 text-sm text-[#607089]"><LoaderCircle className="animate-spin" size={22}/>Cargando documento…</div>}{!previewMode&&items.map((item,index)=>item.pagina===page&&<div key={item.id||`${item.tipo}-${index}`} onPointerDown={event=>move(index,event)} style={{left:`${item.x*100}%`,top:`${item.y*100}%`,width:`${item.ancho*100}%`,height:`${item.alto*100}%`}} className={`absolute select-none ${item.usuario_id===props.userId&&canPlace?"cursor-move":""} ${selected===index&&item.usuario_id===props.userId&&canPlace?"outline outline-1 outline-offset-1 outline-[#2563EB]":""}`}><Image unoptimized fill draggable={false} src={asset(item)} alt={item.tipo==="FIRMA"?"Firma manuscrita":"Sello corporativo"} className="pointer-events-none object-contain"/>{selected===index&&item.usuario_id===props.userId&&canPlace&&<><button type="button" onPointerDown={event=>resize(index,event)} className="absolute -bottom-2 -right-2 h-5 w-5 cursor-se-resize rounded-full border-2 border-white bg-[#2563EB]" aria-label="Cambiar tamaño"/><button type="button" onPointerDown={event=>event.stopPropagation()} onClick={()=>remove(index)} className="absolute -right-2 -top-2 grid h-5 w-5 place-items-center rounded-full border-2 border-white bg-[#C53030] text-white" aria-label={`Quitar ${item.tipo.toLowerCase()}`}><Trash2 size={10}/></button></>}</div>)}</div></div></section>
  <aside className="space-y-3"><div className="section-card xl:sticky xl:top-20"><h2 className="section-title">{canManager?"Revisar documento":canOwner?"Preparar documento":"Documento"}</h2><p className="mt-1 text-sm text-[#607089]">{canManager&&props.coordinatorSigned?"Revisas la versión que ya contiene la firma del coordinador.":canPlace?"Completa los pasos en orden antes de continuar.":"El documento está en modo de consulta."}</p>{canManager&&props.coordinatorSigned&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs leading-5 text-emerald-900"><strong className="font-semibold">Versión recibida del coordinador</strong><span className="block">El visor y la vista previa final parten de esta versión intermedia.</span></div>}
  {canOwner&&<ol className="mt-4 grid gap-1.5 text-xs font-medium text-[#45556D]"><li>1. Guardar ubicación</li><li>2. Vista previa final</li><li>3. Firmar como coordinador <span className="font-normal text-[#607089]">(opcional)</span></li><li>4. Enviar a firma</li></ol>}
  {canManager&&<ol className="mt-4 grid gap-1.5 text-xs font-medium text-[#45556D]"><li>1. Vista previa final</li><li>2. Observar / Rechazar</li><li>3. Firmar documento</li></ol>}
  {!props.profileReady&&canOwner&&!props.coordinatorSigned&&<div className="mt-4"><Alert kind="warning">Configura tu <Link className="underline" href="/perfil/firma">firma y sello</Link> para firmar este documento. Puedes enviarlo sin firma.</Alert></div>}
  {!props.profileReady&&canManager&&<div className="mt-4"><Alert kind="warning">Debes <Link className="underline" href="/perfil/firma">configurar tu firma y sello</Link> antes de firmar.</Alert></div>}
  {props.coordinatorSigned&&canOwner&&<div className="mt-4"><Alert kind="success">Firma del coordinador incorporada. La versión intermedia quedó protegida.</Alert></div>}
  {canPlace&&<div className="mt-4 grid gap-2"><button disabled={busy||!dirty||previewMode} onClick={()=>action("colocaciones",{colocaciones:own})} className="btn btn-secondary w-full"><Save size={17}/>Guardar ubicación</button><button disabled={busy||previewMode||dirty||loadingPdf} onClick={openPreview} className="btn btn-secondary w-full"><Eye size={17}/>Vista previa final</button></div>}
  {canOwner&&!props.coordinatorSigned&&props.profileReady&&<button disabled={busy||dirty||!previewed||previewMode||ownCount===0} onClick={()=>setConfirmSign("coordinador")} className="btn btn-secondary mt-2 w-full"><PenLine size={17}/>Firmar como coordinador</button>}
  {canOwner&&<button disabled={busy||!canSend||previewMode} onClick={()=>action("enviar")} className="btn btn-primary mt-2 w-full"><Send size={17}/>Enviar a firma</button>}
  {canManager&&<><div className="mt-4 grid grid-cols-2 gap-2 border-t border-[#DCE3EC] pt-4"><button disabled={busy} onClick={()=>{setComment("");setDecision("observar")}} className="btn btn-secondary px-2"><MessageSquareWarning size={16}/>Observar</button><button disabled={busy} onClick={()=>{setComment("");setDecision("rechazar")}} className="btn btn-danger px-2"><XCircle size={16}/>Rechazar</button></div><button disabled={busy||dirty||!previewed||previewMode||ownCount===0||!props.profileReady} onClick={()=>setConfirmSign("gerente")} className="btn btn-primary mt-2 w-full"><CheckCircle2 size={17}/>Firmar documento</button></>}
  {canPlace&&(dirty||!previewed)&&<p className="mt-3 text-xs text-[#607089]">{dirty?"Guarda la ubicación actual para continuar.":"Revisa la vista previa final para habilitar la acción principal."}</p>}
  {message&&<div className="mt-4"><Alert kind={message.includes("correctamente")||message.includes("revisada")?"success":"error"}>{message}</Alert></div>}</div>
  <div className="section-card"><h2 className="section-title">Versiones del documento</h2><p className="mt-1 text-xs leading-5 text-[#607089]">Cada versión se conserva por separado y sin reemplazar el original.</p><div className="mt-4 grid gap-2"><a target="_blank" rel="noreferrer" className="btn btn-secondary w-full" href={`/api/documentos/${props.id}/archivo`}><ExternalLink size={17}/>Ver original</a>{props.coordinatorSigned&&<><a target="_blank" rel="noreferrer" className="btn btn-secondary w-full" href={`/api/documentos/${props.id}/archivo?tipo=coordinador`}><Eye size={17}/>Ver versión coordinador</a><a className="btn btn-secondary w-full" href={`/api/documentos/${props.id}/archivo?tipo=coordinador&download=1`}><Download size={17}/>Descargar versión coordinador</a></>}{props.status==="FIRMADO"&&<><a target="_blank" rel="noreferrer" className="btn btn-secondary w-full" href={`/api/documentos/${props.id}/archivo?tipo=firmado`}><Eye size={17}/>Ver firmado final</a><a className="btn btn-primary w-full" href={`/api/documentos/${props.id}/archivo?tipo=firmado&download=1`}><Download size={17}/>Descargar firmado final</a></>}</div></div></aside></div>
 <DecisionDialog kind={decision} comment={comment} busy={busy} onComment={setComment} onCancel={()=>setDecision(null)} onConfirm={async()=>{if(decision&&await action(decision,{comentario:comment}))setDecision(null)}}/>
 <ConfirmDialog open={Boolean(confirmSign)} busy={busy} intent="warning" title={confirmSign==="coordinador"?"Firmar como coordinador":"Confirmar firma del documento"} description={confirmSign==="coordinador"?"Tu firma y/o sello se incorporarán físicamente a una versión intermedia. El original permanecerá intacto y el documento todavía deberá enviarse al gerente.":"Vas a incorporar tu firma y/o sello a la versión preparada del documento. Se generará la versión final, que ya no podrá modificarse."} confirmLabel={confirmSign==="coordinador"?"Firmar como coordinador":"Confirmar firma"} onCancel={()=>setConfirmSign(null)} onConfirm={async()=>{const accion=confirmSign==="coordinador"?"firmar_coordinador":"firmar";if(await action(accion))setConfirmSign(null)}}/>
 </>;
}
