"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, CheckCircle2, ClipboardList, FilePlus2, Home, LoaderCircle, Plus, Search, Trash2, UserRoundSearch } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { requerimientoSchema } from "@/lib/validations";
import { Alert } from "@/components/ui/alert";
import { LoadingState } from "@/components/ui/loading-state";
import type { Personal, Prenda } from "@/lib/types";

type Line = { prenda: Prenda; cantidad: number };
export function NewRequirement() {
  const supabase = useMemo(() => createClient(), []); const garmentCache = useRef(new Map<string, Prenda[]>());
  const [step,setStep]=useState<1|2>(1); const [query,setQuery]=useState(""); const [agents,setAgents]=useState<Personal[]>([]); const [agent,setAgent]=useState<Personal|null>(null);
  const [garments,setGarments]=useState<Prenda[]>([]); const [lines,setLines]=useState<Line[]>([]); const [selected,setSelected]=useState(""); const [qty,setQty]=useState(1);
  const [searching,setSearching]=useState(false); const [selectingAgent,setSelectingAgent]=useState(""); const [loadingGarments,setLoadingGarments]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [successId,setSuccessId]=useState("");

  useEffect(()=>{ const controller=new AbortController(); const term=query.trim(); if(term.length<2)return()=>controller.abort(); const timer=setTimeout(async()=>{const {data,error:searchError}=await supabase.rpc("buscar_personal",{p_busqueda:term,p_limite:20}).abortSignal(controller.signal);if(!controller.signal.aborted){setAgents((data??[]) as Personal[]);setSearching(false);if(searchError)setError("No pudimos realizar la búsqueda. Intenta nuevamente.");}},300);return()=>{clearTimeout(timer);controller.abort();};},[query,supabase]);
  async function choose(a:Personal){if(selectingAgent)return;setSelectingAgent(a.id);setError("");setAgent(a);setLoadingGarments(true);const cached=garmentCache.current.get(a.cliente);if(cached){setGarments(cached);setStep(2);setSelectingAgent("");setLoadingGarments(false);return;}const {data,error:garmentsError}=await supabase.from("prendas").select("id,codigo_prenda,nombre_prenda,codigo_almacen,precio,cliente,activo").eq("activo",true).eq("cliente",a.cliente).order("nombre_prenda").limit(200);if(garmentsError){setError("No pudimos cargar las prendas del cliente.");setAgent(null);setSelectingAgent("");setLoadingGarments(false);return;}const rows=(data??[]) as Prenda[];garmentCache.current.set(a.cliente,rows);setGarments(rows);setStep(2);setSelectingAgent("");setLoadingGarments(false);}
  function add(){const garment=garments.find(g=>g.id===selected);if(!garment||qty<1){setError("Selecciona una prenda e ingresa una cantidad válida.");return;}setLines(current=>{const found=current.find(l=>l.prenda.id===garment.id);return found?current.map(l=>l.prenda.id===garment.id?{...l,cantidad:l.cantidad+qty}:l):[...current,{prenda:garment,cantidad:qty}]});setSelected("");setQty(1);setError("");}
  async function save(){if(!agent||saving)return;const parsed=requerimientoSchema.safeParse({agente_id:agent.id,detalles:lines.map(l=>({prenda_id:l.prenda.id,cantidad:l.cantidad}))});if(!parsed.success){setError(parsed.error.issues[0].message);return;}setSaving(true);setError("");const {data,error:saveError}=await supabase.rpc("crear_requerimiento",{p_agente_id:parsed.data.agente_id,p_detalles:parsed.data.detalles});if(saveError){setError(saveError.message.includes("authorized")?"No tienes permisos para registrar esta solicitud.":"No se pudo guardar el requerimiento. Tus datos siguen aquí para que puedas intentarlo nuevamente.");setSaving(false);return;}setSuccessId(String(data));setSaving(false);}

  if(successId)return <section className="mx-auto max-w-2xl py-3 sm:py-8"><div className="card p-5 sm:p-7"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-emerald-50 text-[#16803C]"><CheckCircle2 size={23}/></span><div><h1 className="text-xl font-semibold text-[#0B1F3A]">Requerimiento registrado</h1><p className="mt-1 text-sm text-[#607089]">El requerimiento de {agent?.nombre} fue guardado correctamente.</p></div></div><div className="mt-6 flex flex-col gap-2 border-t border-[#DCE3EC] pt-5 sm:flex-row"><Link className="btn btn-primary" href="/requerimientos/nuevo"><FilePlus2 size={17}/>Crear otro requerimiento</Link><Link className="btn btn-secondary" href={`/requerimientos/${successId}`}>Ver requerimiento</Link><Link className="btn btn-ghost" href="/requerimientos"><ClipboardList size={17}/>Mis requerimientos</Link><Link className="btn btn-ghost sm:ml-auto" href="/inicio"><Home size={17}/>Inicio</Link></div></div></section>;

  if(step===1)return <section className="mx-auto max-w-[880px]"><Link href="/inicio" className="btn btn-ghost mb-3 -ml-3"><ArrowLeft size={16}/>Volver al inicio</Link><header className="page-header"><p className="page-eyebrow">Nuevo requerimiento · Paso 1 de 2</p><h1 className="page-title">Selecciona un agente</h1><p className="page-description">Busca al agente que recibirá las prendas.</p></header><div className="section-card"><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#607089]" size={18}/><input autoFocus className="input !pl-11" value={query} onChange={e=>{const value=e.target.value;setQuery(value);setAgents([]);setSearching(value.trim().length>=2);setError("");}} placeholder="Nombre, DNI o código..." aria-label="Buscar agente"/></div>{searching&&<LoadingState compact label="Buscando..."/>}</div>{error&&<div className="mt-3"><Alert kind="error">{error}</Alert></div>}<div className="mt-3 space-y-2">{!searching&&query.trim().length>=2&&!agents.length&&<div className="rounded-xl border border-dashed border-[#DCE3EC] bg-white p-5 text-center"><UserRoundSearch className="mx-auto text-[#8794A8]" size={24}/><p className="mt-2 text-sm font-semibold text-[#172033]">No encontramos agentes con ese criterio.</p><p className="mt-1 text-xs text-[#607089]">Prueba con otro nombre, DNI o código.</p></div>}{agents.map(a=><button key={a.id} disabled={Boolean(selectingAgent)} onClick={()=>choose(a)} className="flex min-h-16 w-full items-center justify-between gap-3 rounded-xl border border-[#DCE3EC] bg-white px-4 py-3 text-left hover:border-[#AFC1D8] disabled:opacity-60"><span><strong className="block text-sm font-semibold text-[#172033]">{a.nombre}</strong><span className="mt-0.5 block text-xs text-[#607089]">DNI {a.dni} · {a.codigo_personal}</span></span>{selectingAgent===a.id?<LoaderCircle className="shrink-0 animate-spin text-[#2563EB]" size={18}/>:<span className="text-xs font-semibold text-[#174EA6]">Seleccionar</span>}</button>)}</div>{loadingGarments&&<div className="mt-3"><LoadingState label="Cargando prendas..."/></div>}</section>;

  const chosen=garments.find(g=>g.id===selected);
  return <section className="mx-auto max-w-[920px]"><button disabled={saving} onClick={()=>{setStep(1);setAgent(null);setLines([]);setError("");}} className="btn btn-ghost mb-3 -ml-3"><ArrowLeft size={16}/>Cambiar agente</button><header className="page-header"><p className="page-eyebrow">Nuevo requerimiento · Paso 2 de 2</p><h1 className="page-title">Selecciona las prendas</h1></header>
    <div className="section-card"><h2 className="section-title">Datos del agente</h2><dl className="mt-3 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">{[["Fecha",new Intl.DateTimeFormat("es-PE",{dateStyle:"long"}).format(new Date())],["Agente",agent?.nombre],["DNI",agent?.dni],["Cargo",agent?.cargo],["Cliente",agent?.cliente],["Unidad",agent?.unidad]].map(([k,v])=><div key={k} className="border-t border-[#E8EDF4] py-2.5"><dt className="text-xs font-medium text-[#607089]">{k}</dt><dd className="mt-0.5 text-sm font-medium text-[#172033]">{v}</dd></div>)}</dl></div>
    <div className="section-card mt-4"><div><h2 className="section-title">Prendas solicitadas</h2><p className="mt-1 text-sm text-[#607089]">Agrega una o más prendas y su cantidad.</p></div>{loadingGarments?<LoadingState label="Cargando prendas..."/>:<div className="mt-4 grid grid-cols-[minmax(0,1fr)_88px] gap-2 sm:grid-cols-[minmax(0,1fr)_96px_auto]"><select aria-label="Prenda" className="input col-span-2 sm:col-span-1" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona una prenda...</option>{garments.map(g=><option key={g.id} value={g.id}>{g.nombre_prenda}</option>)}</select><input aria-label="Cantidad" className="input" type="number" min="1" step="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><button disabled={!selected||qty<1} onClick={add} className="btn btn-primary"><Plus size={17}/>Agregar</button></div>}{chosen&&<p className="mt-2 text-xs text-[#607089]">Código {chosen.codigo_almacen} · Precio unitario S/ {Number(chosen.precio).toFixed(2)}</p>}<div className="mt-4 divide-y divide-[#E8EDF4] border-y border-[#E8EDF4]">{!lines.length?<div className="py-4 text-center"><p className="text-sm font-medium text-[#45556D]">Todavía no agregaste prendas.</p><p className="mt-0.5 text-xs text-[#607089]">Selecciona una prenda para comenzar.</p></div>:lines.map(l=><div key={l.prenda.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><strong className="text-sm font-medium text-[#172033]">{l.prenda.nombre_prenda}</strong><p className="mt-0.5 text-xs text-[#607089]">{l.prenda.codigo_almacen} · Cantidad {l.cantidad} · S/ {Number(l.prenda.precio).toFixed(2)}</p></div><button disabled={saving} aria-label={`Eliminar ${l.prenda.nombre_prenda}`} onClick={()=>setLines(x=>x.filter(i=>i.prenda.id!==l.prenda.id))} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-[#C53030] hover:bg-red-50"><Trash2 size={17}/></button></div>)}</div></div>{error&&<div className="mt-3"><Alert kind="error">{error}</Alert></div>}<footer className="mt-4 flex flex-col-reverse gap-2 border-t border-[#DCE3EC] pt-4 sm:flex-row sm:justify-end"><button disabled={saving} onClick={()=>{setStep(1);setAgent(null);setLines([]);setError("");}} className="btn btn-secondary">Cancelar</button><button onClick={save} disabled={saving||!lines.length} className="btn btn-primary w-full sm:w-auto">{saving?<LoaderCircle className="animate-spin"/>:<CheckCircle2 size={17}/>} {saving?"Guardando requerimiento...":"Guardar requerimiento"}</button></footer>
  </section>;
}
