"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Alert } from "./ui/alert";
type Person={id:string;nombre:string;dni:string;cargo:string;codigo_personal:string};
export function NewDocumentForm({managers}:{managers:{id:string;nombre:string}[]}){
 const [query,setQuery]=useState("");const [people,setPeople]=useState<Person[]>([]);const [person,setPerson]=useState<Person|null>(null);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const router=useRouter();
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 function search(value:string){setQuery(value);setPerson(null);if(timer.current)clearTimeout(timer.current);if(value.trim().length<2){setPeople([]);return}timer.current=setTimeout(async()=>{setLoading(true);const {data}=await createClient().rpc("buscar_personal",{p_busqueda:value.trim(),p_limite:20});setPeople((data||[]) as Person[]);setLoading(false)},250)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!person){setError("Selecciona un trabajador de los resultados.");return}setBusy(true);setError("");const form=new FormData(e.currentTarget);form.set("trabajador_id",person.id);try{const response=await fetch("/api/documentos",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);router.push(`/documentos/${data.id}`);router.refresh()}catch(ex){setError(ex instanceof Error?ex.message:"No se pudo crear.")}finally{setBusy(false)}}
 return <form onSubmit={submit} className="grid gap-4 lg:grid-cols-[1fr_340px]"><section className="section-card"><h2 className="section-title">Datos del documento</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Trabajador</label><input className="input" value={person?person.nombre:query} onChange={e=>search(e.target.value)} placeholder="Buscar por nombre, DNI o código" autoComplete="off"/>{loading&&<p className="metadata mt-2">Buscando…</p>}{!person&&people.length>0&&<div className="mt-2 max-h-52 overflow-auto rounded-xl border border-[#DCE3EC] bg-white p-1 shadow-lg">{people.map(p=><button key={p.id} type="button" onClick={()=>{setPerson(p);setQuery(p.nombre);setPeople([])}} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-[#F5F8FD]"><strong className="block text-sm font-medium">{p.nombre}</strong><span className="text-xs text-[#607089]">{p.dni} · {p.cargo}</span></button>)}</div>}</div>
 <div><label className="label" htmlFor="tipo">Tipo</label><select className="input" id="tipo" name="tipo" required defaultValue=""><option value="" disabled>Seleccionar</option><option value="VACACIONES">Vacaciones</option><option value="LICENCIA_CON_GOCE">Licencia con goce</option><option value="LICENCIA_SIN_GOCE">Licencia sin goce</option></select></div>
 <div><label className="label" htmlFor="firmante">Gerente firmante</label><select className="input" id="firmante" name="firmante_id" required defaultValue=""><option value="" disabled>Seleccionar</option>{managers.map(m=><option value={m.id} key={m.id}>{m.nombre}</option>)}</select></div>
 <div className="sm:col-span-2"><label className="label" htmlFor="observacion">Observación opcional</label><textarea className="input min-h-24 resize-y py-3" id="observacion" name="observacion" maxLength={1000}/></div></div></section>
 <aside className="section-card h-fit"><h2 className="section-title">Archivo original</h2><p className="mt-1 text-sm text-[#607089]">PDF auténtico, sin cifrar. Máximo configurado por el sistema.</p><input className="mt-5 block w-full text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-[#EAF2FF] file:px-4 file:py-2.5 file:font-semibold file:text-[#174EA6]" type="file" name="archivo" accept="application/pdf,.pdf" required/>{error&&<div className="mt-4"><Alert kind="error">{error}</Alert></div>}<button disabled={busy||!managers.length} className="btn btn-primary mt-5 w-full">{busy?"Creando…":"Crear borrador"}</button></aside></form>
}
