"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, CheckCircle2, ClipboardList, FilePlus2, Home, LoaderCircle, Plus, Search, Trash2, UserRoundSearch } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { requerimientoSchema } from "@/lib/validations";
import { Alert } from "@/components/ui/alert";
import { LoadingState } from "@/components/ui/loading-state";
import type { Personal, Prenda } from "@/lib/types";

type Line = { prenda: Prenda; cantidad: number };
export function NewRequirement() {
  const supabase = useMemo(() => createClient(), []); const garmentCache = useRef(new Map<string, Prenda[]>());
  const [step,setStep]=useState<1|2>(1); const [query,setQuery]=useState(""); const [agents,setAgents]=useState<Personal[]>([]); const [agent,setAgent]=useState<Personal|null>(null);
  const [garments,setGarments]=useState<Prenda[]>([]); const [lines,setLines]=useState<Line[]>([]); const [selected,setSelected]=useState(""); const [qty,setQty]=useState(1);
  const [searching,setSearching]=useState(false); const [selectingAgent,setSelectingAgent]=useState(""); const [loadingGarments,setLoadingGarments]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [successId,setSuccessId]=useState("");

  useEffect(()=>{ const controller=new AbortController(); const term=query.trim(); if(term.length<2)return()=>controller.abort(); const timer=setTimeout(async()=>{const {data,error:searchError}=await supabase.rpc("buscar_personal",{p_busqueda:term,p_limite:20}).abortSignal(controller.signal);if(!controller.signal.aborted){setAgents((data??[]) as Personal[]);setSearching(false);if(searchError)setError("No pudimos realizar la búsqueda. Intenta nuevamente.");}},300);return()=>{clearTimeout(timer);controller.abort();};},[query,supabase]);
  async function choose(a:Personal){if(selectingAgent)return;setSelectingAgent(a.id);setError("");setAgent(a);setLoadingGarments(true);const cached=garmentCache.current.get(a.cliente);if(cached){setGarments(cached);setStep(2);setSelectingAgent("");setLoadingGarments(false);return;}const {data,error:garmentsError}=await supabase.from("prendas").select("id,codigo_prenda,nombre_prenda,codigo_almacen,precio,cliente,activo").eq("activo",true).eq("cliente",a.cliente).order("nombre_prenda").limit(200);if(garmentsError){setError("No pudimos cargar las prendas del cliente.");setAgent(null);setSelectingAgent("");setLoadingGarments(false);return;}const rows=(data??[]) as Prenda[];garmentCache.current.set(a.cliente,rows);setGarments(rows);setStep(2);setSelectingAgent("");setLoadingGarments(false);}
  function add(){const garment=garments.find(g=>g.id===selected);if(!garment||qty<1){setError("Selecciona una prenda e ingresa una cantidad válida.");return;}setLines(current=>{const found=current.find(l=>l.prenda.id===garment.id);return found?current.map(l=>l.prenda.id===garment.id?{...l,cantidad:l.cantidad+qty}:l):[...current,{prenda:garment,cantidad:qty}]});setSelected("");setQty(1);setError("");}
  async function save(){if(!agent||saving)return;const parsed=requerimientoSchema.safeParse({agente_id:agent.id,detalles:lines.map(l=>({prenda_id:l.prenda.id,cantidad:l.cantidad}))});if(!parsed.success){setError(parsed.error.issues[0].message);return;}setSaving(true);setError("");const {data,error:saveError}=await supabase.rpc("crear_requerimiento",{p_agente_id:parsed.data.agente_id,p_detalles:parsed.data.detalles});if(saveError){setError(saveError.message.includes("authorized")?"No tienes permisos para registrar esta solicitud.":"No se pudo guardar el requerimiento. Tus datos siguen aquí para que puedas intentarlo nuevamente.");setSaving(false);return;}setSuccessId(String(data));setSaving(false);}

  if(successId)return <section className="mx-auto max-w-2xl py-4 sm:py-10"><div className="card overflow-hidden"><div className="border-b border-emerald-100 bg-emerald-50 p-6 text-center sm:p-8"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-600 text-white"><CheckCircle2 size={34}/></span><h1 className="mt-5 text-2xl font-black text-slate-900">Requerimiento registrado correctamente.</h1><p className="mt-2 text-sm text-slate-600">La solicitud de {agent?.nombre} fue guardada y ya aparece en tu historial.</p></div><div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-7"><Link className="btn btn-primary" href="/requerimientos/nuevo"><FilePlus2 size={19}/>Crear otro requerimiento</Link><Link className="btn btn-secondary" href="/inicio"><Home size={19}/>Ir al inicio</Link><Link className="btn btn-secondary" href="/requerimientos"><ClipboardList size={19}/>Ver mis requerimientos</Link></div><div className="px-5 pb-6 text-center"><Link className="text-sm font-bold text-blue-700 hover:underline" href={`/requerimientos/${successId}`}>Ver detalle del requerimiento</Link></div></div></section>;

  if(step===1)return <section className="mx-auto max-w-3xl"><Link href="/inicio" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700 hover:underline"><ArrowLeft size={17}/>Volver al inicio</Link><header className="mb-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-blue-600">Nuevo requerimiento · Paso 1 de 2</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Selecciona un agente</h1><p className="mt-2 text-slate-500">Busca al agente que recibirá las prendas.</p></header><div className="card p-4 sm:p-5"><div className="relative"><Search aria-hidden="true" className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={21}/><input autoFocus className="input min-h-14 !pl-13 pr-4" value={query} onChange={e=>{const value=e.target.value;setQuery(value);setAgents([]);setSearching(value.trim().length>=2);setError("");}} placeholder="Nombre, DNI o código..." aria-label="Buscar agente"/></div>{searching&&<LoadingState compact label="Buscando..."/>}</div>{error&&<div className="mt-4"><Alert kind="error">{error}</Alert></div>}<div className="mt-4 space-y-2">{!searching&&query.trim().length>=2&&!agents.length&&<div className="card p-8 text-center"><UserRoundSearch className="mx-auto text-slate-400" size={32}/><p className="mt-3 font-bold text-slate-700">No encontramos agentes con ese criterio.</p><p className="mt-1 text-sm text-slate-500">Prueba con otro nombre, DNI o código.</p></div>}{agents.map(a=><button key={a.id} disabled={Boolean(selectingAgent)} onClick={()=>choose(a)} className="card flex min-h-20 w-full items-center justify-between gap-3 p-4 text-left transition hover:border-blue-300 hover:shadow-md disabled:opacity-60"><span><strong className="block text-slate-900">{a.nombre}</strong><span className="mt-1 block text-sm text-slate-500">DNI {a.dni} · {a.codigo_personal}</span></span>{selectingAgent===a.id?<LoaderCircle className="shrink-0 animate-spin text-blue-600"/>:<span className="text-sm font-bold text-blue-700">Seleccionar</span>}</button>)}</div>{loadingGarments&&<div className="mt-4"><LoadingState label="Cargando prendas..."/></div>}</section>;

  const chosen=garments.find(g=>g.id===selected);
  return <section className="mx-auto max-w-3xl"><button disabled={saving} onClick={()=>{setStep(1);setAgent(null);setLines([]);setError("");}} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700 hover:underline disabled:opacity-50"><ArrowLeft size={17}/>Cambiar agente</button><header><p className="text-xs font-extrabold uppercase tracking-[.16em] text-blue-600">Nuevo requerimiento · Paso 2 de 2</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Selecciona las prendas</h1></header>
    <div className="card mt-5 p-5 sm:p-6"><h2 className="mb-5 text-lg font-extrabold">Datos del agente</h2><dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Fecha",new Intl.DateTimeFormat("es-PE",{dateStyle:"long"}).format(new Date())],["Agente",agent?.nombre],["DNI",agent?.dni],["Cargo",agent?.cargo],["Cliente",agent?.cliente],["Unidad",agent?.unidad]].map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 px-3 py-2"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{k}</dt><dd className="mt-1 font-semibold text-slate-800">{v}</dd></div>)}</dl></div>
    <div className="card mt-5 p-5 sm:p-6"><div><h2 className="text-lg font-extrabold">Prendas solicitadas</h2><p className="mt-1 text-sm text-slate-500">Agrega una o más prendas y su cantidad.</p></div>{loadingGarments?<LoadingState label="Cargando prendas..."/>:<div className="mt-5 grid gap-3 sm:grid-cols-[1fr_110px_auto]"><select aria-label="Prenda" className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona una prenda...</option>{garments.map(g=><option key={g.id} value={g.id}>{g.nombre_prenda}</option>)}</select><input aria-label="Cantidad" className="input" type="number" min="1" step="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><button disabled={!selected||qty<1} onClick={add} className="btn btn-primary"><Plus size={19}/>Agregar</button></div>}{chosen&&<p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">Código {chosen.codigo_almacen} · Precio unitario S/ {Number(chosen.precio).toFixed(2)}</p>}<div className="mt-5 space-y-2">{!lines.length?<div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><p className="font-bold text-slate-700">Aún no has agregado prendas.</p><p className="mt-1 text-sm text-slate-500">Selecciona una prenda y pulsa Agregar.</p></div>:lines.map(l=><div key={l.prenda.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><div className="min-w-0 flex-1"><strong>{l.prenda.nombre_prenda}</strong><p className="mt-1 text-sm text-slate-500">Cantidad: {l.cantidad} · {l.prenda.codigo_almacen} · S/ {Number(l.prenda.precio).toFixed(2)}</p></div><button disabled={saving} aria-label={`Eliminar ${l.prenda.nombre_prenda}`} onClick={()=>setLines(x=>x.filter(i=>i.prenda.id!==l.prenda.id))} className="grid h-11 w-11 shrink-0 place-items-center rounded-lg text-red-600 hover:bg-red-50"><Trash2 size={19}/></button></div>)}</div></div>{error&&<div className="mt-4"><Alert kind="error">{error}</Alert></div>}<button onClick={save} disabled={saving||!lines.length} className="btn btn-primary mt-5 w-full min-h-14">{saving?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}{saving?"Guardando requerimiento...":"Guardar requerimiento"}</button>
  </section>;
}
