"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, LoaderCircle, Plus, Search, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { requerimientoSchema } from "@/lib/validations";
import type { Personal, Prenda } from "@/lib/types";

type Line = { prenda: Prenda; cantidad: number };
export function NewRequirement() {
  const router=useRouter(); const supabase=useMemo(()=>createClient(),[]);
  const [step,setStep]=useState<1|2>(1); const [query,setQuery]=useState(""); const [agents,setAgents]=useState<Personal[]>([]); const [agent,setAgent]=useState<Personal|null>(null);
  const [garments,setGarments]=useState<Prenda[]>([]); const [lines,setLines]=useState<Line[]>([]); const [selected,setSelected]=useState(""); const [qty,setQty]=useState(1); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  const garmentCache=useRef(new Map<string,Prenda[]>());
  useEffect(()=>{ const controller=new AbortController(); const timer=setTimeout(async()=>{ if(query.trim().length<2){setAgents([]);return;} const {data}=await supabase.rpc("buscar_personal",{p_busqueda:query.trim(),p_limite:20}).abortSignal(controller.signal); if(!controller.signal.aborted)setAgents((data??[]) as Personal[]); },250); return()=>{clearTimeout(timer);controller.abort();}; },[query,supabase]);
  async function choose(a:Personal){ setAgent(a); setStep(2); const cached=garmentCache.current.get(a.cliente); if(cached){setGarments(cached);return;} const {data}=await supabase.from("prendas").select("id,codigo_prenda,nombre_prenda,codigo_almacen,precio,cliente,activo").eq("activo",true).eq("cliente",a.cliente).order("nombre_prenda").limit(200); const rows=(data??[]) as Prenda[];garmentCache.current.set(a.cliente,rows);setGarments(rows); }
  function add(){ const garment=garments.find(g=>g.id===selected); if(!garment||qty<1)return; setLines(current=>{const found=current.find(l=>l.prenda.id===garment.id); return found ? current.map(l=>l.prenda.id===garment.id?{...l,cantidad:l.cantidad+qty}:l) : [...current,{prenda:garment,cantidad:qty}]}); setSelected("");setQty(1);setMessage(""); }
  async function save(){ if(!agent)return; const payload={agente_id:agent.id,detalles:lines.map(l=>({prenda_id:l.prenda.id,cantidad:l.cantidad}))}; const parsed=requerimientoSchema.safeParse(payload); if(!parsed.success){setMessage(parsed.error.issues[0].message);return;} setLoading(true); setMessage(""); const {data,error}=await supabase.rpc("crear_requerimiento",{p_agente_id:parsed.data.agente_id,p_detalles:parsed.data.detalles}); if(error){setMessage(error.message.includes("authorized")?"No tienes permisos para registrar esta solicitud.":"No se pudo guardar el requerimiento. Intenta nuevamente.");setLoading(false);return;} setMessage("¡Requerimiento guardado correctamente!"); setTimeout(()=>router.replace(`/requerimientos/${data}`),700); }
  if(step===1)return <section><header className="mb-6"><h1 className="text-2xl font-black">Selecciona un agente</h1><p className="mt-1 text-slate-500">Busca al agente que recibirá las prendas.</p></header><div className="relative"><Search className="absolute left-4 top-4 text-slate-400"/><input autoFocus className="input min-h-14 pl-12" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre, apellido, DNI o código..."/></div><div className="mt-4 space-y-2">{query.length>=2&&!agents.length&&<div className="card p-8 text-center text-slate-500">No se encontraron agentes activos.</div>}{agents.map(a=><button key={a.id} onClick={()=>choose(a)} className="card w-full p-4 text-left transition hover:border-blue-300"><strong className="block">{a.nombre}</strong><span className="mt-1 block text-sm text-slate-500">DNI {a.dni} · {a.codigo_personal}</span></button>)}</div></section>;
  const chosen=garments.find(g=>g.id===selected);
  return <section className="mx-auto max-w-3xl"><button onClick={()=>{setStep(1);setAgent(null);setLines([])}} className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-blue-700"><ArrowLeft size={17}/>Cambiar agente</button><h1 className="text-2xl font-black">Nuevo requerimiento</h1>
    <div className="card mt-5 p-5"><h2 className="mb-4 font-extrabold">Datos del agente</h2><dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Fecha",new Intl.DateTimeFormat("es-PE",{dateStyle:"long"}).format(new Date())],["Agente",agent?.nombre],["DNI",agent?.dni],["Cargo",agent?.cargo],["Cliente",agent?.cliente],["Unidad",agent?.unidad]].map(([k,v])=><div key={k}><dt className="font-bold text-slate-500">{k}</dt><dd className="mt-1">{v}</dd></div>)}</dl></div>
    <div className="card mt-5 p-5"><h2 className="font-extrabold">Prendas solicitadas</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_110px_auto]"><select className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona una prenda...</option>{garments.map(g=><option key={g.id} value={g.id}>{g.nombre_prenda}</option>)}</select><input aria-label="Cantidad" className="input" type="number" min="1" step="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><button onClick={add} className="btn btn-primary"><Plus size={19}/>Agregar</button></div>{chosen&&<p className="mt-2 text-sm text-slate-500">Código {chosen.codigo_almacen} · S/ {Number(chosen.precio).toFixed(2)}</p>}
      <div className="mt-5 space-y-2">{!lines.length?<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Aún no has agregado prendas.</p>:lines.map(l=><div key={l.prenda.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><div className="min-w-0 flex-1"><strong>{l.prenda.nombre_prenda}</strong><p className="text-sm text-slate-500">Cantidad: {l.cantidad} · {l.prenda.codigo_almacen} · S/ {Number(l.prenda.precio).toFixed(2)}</p></div><button aria-label={`Eliminar ${l.prenda.nombre_prenda}`} onClick={()=>setLines(x=>x.filter(i=>i.prenda.id!==l.prenda.id))} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={19}/></button></div>)}</div>
    </div>
    {message&&<p role="status" className={`mt-4 rounded-xl p-4 text-sm ${message.startsWith("¡")?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-700"}`}>{message}</p>}
    <button onClick={save} disabled={loading||!lines.length} className="btn btn-primary mt-5 w-full min-h-14">{loading?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}{loading?"Guardando...":"Guardar requerimiento"}</button>
  </section>;
}
