"use client";
import Image from "next/image";
import { useEffect,useRef,useState } from "react";
import { Check,Edit3,Eraser,ImageUp,PenLine,RefreshCw,ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { Alert } from "./ui/alert";
import { CorporateStampPreview } from "./corporate-stamp-preview";

type SignatureMode="DIBUJADA"|"IMPORTADA";

export function SignatureProfileForm({initialName,initialRole,configured,hasSignature=configured,initialMode="DIBUJADA",updatedAt}:{initialName:string;initialRole:string;configured:boolean;hasSignature?:boolean;initialMode?:SignatureMode;updatedAt?:string|null}){
 const canvasRef=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);const ink=useRef(false);const objectUrl=useRef<string|null>(null);
 const [mode,setMode]=useState<SignatureMode>(initialMode);const [savedMode,setSavedMode]=useState<SignatureMode>(initialMode);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<string|null>(hasSignature?"/api/perfil/firma?tipo=firma":null);const [name,setName]=useState(initialName);const [role,setRole]=useState(initialRole);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const router=useRouter();
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#0B1F3A";ctx.lineWidth=2.4},[mode]);useEffect(()=>()=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current)},[]);
 function point(e:React.PointerEvent<HTMLCanvasElement>){const rect=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-rect.left)*e.currentTarget.width/rect.width,y:(e.clientY-rect.top)*e.currentTarget.height/rect.height}}
 function start(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;ink.current=true;setFile(null);e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);const ctx=canvasRef.current?.getContext("2d");ctx?.beginPath();ctx?.moveTo(p.x,p.y)}
 function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const p=point(e);const ctx=canvasRef.current?.getContext("2d");ctx?.lineTo(p.x,p.y);ctx?.stroke()}
 function finish(){drawing.current=false;if(ink.current)setPreview(canvasRef.current?.toDataURL("image/png")||null)}
 function clear(){canvasRef.current?.getContext("2d")?.clearRect(0,0,800,260);ink.current=false;setFile(null);setPreview(savedMode===mode&&hasSignature?`/api/perfil/firma?tipo=firma&v=${Date.now()}`:null)}
 function selectMode(next:SignatureMode){setMode(next);setFile(null);ink.current=false;setMessage("");setPreview(savedMode===next&&hasSignature?`/api/perfil/firma?tipo=firma&v=${Date.now()}`:null)}
 function choose(next:File|null){if(!next)return;if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current=URL.createObjectURL(next);setMode("IMPORTADA");setFile(next);setPreview(objectUrl.current);ink.current=false}
 async function save(){
  setBusy(true);setMessage("");try{const form=new FormData();form.set("modo",mode);if(mode==="DIBUJADA"){form.set("nombre",name);form.set("cargo",role)}
   if(file)form.set("firma",file);else if(mode==="DIBUJADA"&&ink.current){const blob=await new Promise<Blob|null>(resolve=>canvasRef.current?.toBlob(resolve,"image/png"));if(blob)form.set("firma",new File([blob],"firma.png",{type:"image/png"}))}
   const response=await fetch("/api/perfil/firma",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error);setSavedMode(mode);setFile(null);ink.current=false;setMessage(mode==="IMPORTADA"?"Imagen final actualizada sin modificaciones.":"Firma y sello corporativo actualizados.");setPreview(`/api/perfil/firma?tipo=firma&v=${Date.now()}`);router.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:"No se pudo guardar.")}finally{setBusy(false)}
 }
 const imported=mode==="IMPORTADA";const needsImportedFile=imported&&savedMode!=="IMPORTADA"&&!file;
 return <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_400px]"><section className="section-card"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#EAF2FF] text-[#174EA6]"><PenLine size={18}/></span><div><h2 className="section-title">Origen de la firma</h2><p className="metadata mt-1">Elige una imagen final lista para usar o genera un sello desde una firma dibujada.</p></div></div>
  <div className="mt-5 grid gap-2 sm:grid-cols-2" role="radiogroup" aria-label="Origen del activo de firma"><button type="button" role="radio" aria-checked={imported} onClick={()=>selectMode("IMPORTADA")} className={`rounded-xl border p-3 text-left transition-colors ${imported?"border-[#2563EB] bg-[#EAF2FF]":"border-[#DCE3EC] bg-white hover:bg-[#F5F8FD]"}`}><span className="flex items-center gap-2 text-sm font-semibold text-[#172033]"><ImageUp size={17}/>Imagen completa{imported&&<Check className="ml-auto text-[#16803C]" size={16}/>}</span><span className="mt-1 block text-xs leading-5 text-[#607089]">PNG/WebP con firma sola o firma y sello ya terminados.</span></button><button type="button" role="radio" aria-checked={!imported} onClick={()=>selectMode("DIBUJADA")} className={`rounded-xl border p-3 text-left transition-colors ${!imported?"border-[#2563EB] bg-[#EAF2FF]":"border-[#DCE3EC] bg-white hover:bg-[#F5F8FD]"}`}><span className="flex items-center gap-2 text-sm font-semibold text-[#172033]"><Edit3 size={17}/>Dibujar firma{!imported&&<Check className="ml-auto text-[#16803C]" size={16}/>}</span><span className="mt-1 block text-xs leading-5 text-[#607089]">La plataforma genera el sello con nombre y cargo.</span></button></div>
  {imported?<div className="mt-5 rounded-xl border border-[#DCE3EC] bg-[#F8FAFC] p-4"><h3 className="text-sm font-semibold text-[#172033]">Imagen final sin composición</h3><p className="mt-1 text-sm leading-6 text-[#607089]">Se conservará la imagen tal como la subas. No se agregarán textos, nombre, cargo, logo ni plantilla corporativa.</p><label className="btn btn-secondary mt-4 w-full cursor-pointer sm:w-auto"><ImageUp size={17}/>{configured?"Seleccionar nueva imagen":"Seleccionar imagen PNG/WebP"}<input className="sr-only" type="file" accept="image/png,image/webp" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{file&&<p className="mt-2 truncate text-xs font-medium text-[#45556D]">{file.name}</p>}{needsImportedFile&&<p className="mt-3 text-xs text-[#B7791F]">Selecciona una imagen completa para cambiar a este modo.</p>}</div>:<><div className="mt-5"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold text-[#172033]">Firma manuscrita</h3><p className="metadata mt-1">Dibuja dentro del área. Esta firma formará parte del sello automático.</p></div><button type="button" onClick={clear} className="btn btn-ghost px-3"><Eraser size={17}/>Limpiar</button></div><div className="mt-3 overflow-hidden rounded-xl border border-[#CBD5E1] bg-white"><canvas ref={canvasRef} width={800} height={260} className="block h-44 w-full touch-none cursor-crosshair" onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} aria-label="Área para dibujar la firma"/></div></div><div className="mt-6 grid gap-4 border-t border-[#DCE3EC] pt-5 sm:grid-cols-2"><div><label className="label">Nombre visible</label><input className="input" maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">Cargo</label><input className="input" maxLength={120} value={role} onChange={e=>setRole(e.target.value)}/></div></div></>}
 </section><aside className="section-card h-fit"><div className="flex items-center justify-between gap-3"><div><h2 className="section-title">{imported?"Vista previa del activo final":"Vista previa del sello"}</h2><p className="metadata mt-1">{imported?"La imagen se usará sin alteraciones":"Plantilla corporativa generada"}</p></div><ShieldCheck size={20} className="text-[#16803C]"/></div>
 <div className="stamp-preview-grid relative mt-4 min-h-44 overflow-hidden rounded-xl">{imported?(preview?<Image unoptimized fill src={preview} alt="Imagen final de firma importada" className="object-contain p-3"/>:<div className="grid min-h-44 place-items-center px-5 text-center text-sm text-[#607089]">Selecciona una imagen para previsualizarla.</div>):<CorporateStampPreview name={name} role={role} signatureSrc={preview}/>}</div>
 <div className="mt-3 flex items-start gap-2 text-xs leading-5 text-[#607089]"><RefreshCw size={14} className="mt-0.5 shrink-0"/><p>{imported?"La transparencia y el contenido visual se conservan; WebP se convierte de forma lossless a PNG para incrustarlo en el PDF.":"El logo, la firma, el nombre y el cargo se componen únicamente en este modo."}</p></div>
 {updatedAt&&<p className="mt-3 text-xs text-[#607089]">Última actualización: {new Intl.DateTimeFormat("es-PE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(updatedAt))}</p>}
 {message&&<div className="mt-4"><Alert kind={message.includes("actualizada")||message.includes("actualizados")?"success":"error"}>{message}</Alert></div>}<button disabled={busy||needsImportedFile} onClick={save} className="btn btn-primary mt-5 w-full">{busy?"Guardando…":configured?"Actualizar perfil":"Guardar perfil"}</button></aside></div>
}
